### ISSUE TITLE
Use OS-agnostic IO handlers

### ISSUE THREAD

**Issue by hausdorf** [basepi/libgit2#14]
PROBLEM:

Current implementation of `src/diff.c` uses a method called `load_file()`. This opens a file given a directory. Arguably, though, this is a function that belongs in a file whose job it is to supply OS-agnostic IO handlers. As it turns out, this instinct is correct, as there is such a file, which you will see in the "resources" section.

OBJECTIVES:
- Transition `diff.c` to OS-agnostic IO handlers, to the exclusion of `diff.c`'s `load_file()`.
- Transition any other file that does this which I overlooked in this bug report.

RESOURCES:
- `fileops.h` and `fileops.c` supplies the OS-agnostic IO handlers required to complete this bug report. They're pretty easy to use.

**Comment by basepi** [comment]
Thanks for finding those fileops files, they were incredibly useful and, as far as I could see, feature-complete.

As far as I can tell, this issue is fixed.  I have removed the load_files() method and the file_exists() method, refactoring all their uses with the equivalent methods from fileops.[h,c].  Closing it for now, if I've missed something, someone please re-open it, eh?

**Comment by hausdorf** [comment]
Glad to hear it.
